Repository AY2021S1-CS2103T-T12-4/tp, pull requests merged in 2020-11, with the labels that each got.

#172 Update filtering and Sort patient by name
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/ChangeCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentComparator.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/patient/Name.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/UniquePatientList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/model/appointment/AppointmentComparatorTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/patient/NameTest.java
  src/test/java/seedu/address/model/patient/PatientTest.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: type.Enhancement :+1:

#173 Add a test class for UniqueAppointmentList
  src/test/java/seedu/address/model/appointment/UniqueAppointmentListTest.java
Labels: type.Testing :pencil2:

#182 Personal Project Portfolio - JH
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/jinhao-l.md
Labels: type.Documentation :memo:

#175 Improve UI (appt status, result display)
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/AppointmentListPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/ResultDisplay.fxml
Labels: type.Enhancement :+1:

#140 Ug update undo/redo with UI screenshots
  docs/UserGuide.md
  docs/images/RedoStep2_UG.png
  docs/images/RedoStep3_UG.png
  docs/images/RedoStep4_UG.png
  docs/images/UndoRedoInitialState_UG.png
  docs/images/UndoStep2_UG.png
  docs/images/UndoStep3_UG.png
Labels: type.Documentation :memo:

#180 Improve functionality of schedule manager
  src/main/java/seedu/address/model/ScheduleManager.java
  src/main/java/seedu/address/model/interval/TimeIntervalList.java
  src/test/java/seedu/address/model/ScheduleManagerTest.java
Labels: type.Enhancement :+1:

#186 Fix available related bugs
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/parser/AvailableCommandParser.java
  src/test/java/seedu/address/logic/parser/AvailableCommandParserTest.java
Labels: type.Bug :bug:

#181 Increases test coverage
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/storage/StorageStatsManager.java
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/FileUtilTest.java
  src/test/java/seedu/address/logic/commands/EditPatientDescriptorTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/DateParserUtilTest.java
  src/test/java/seedu/address/logic/parser/NuudleParserTest.java
  src/test/java/seedu/address/logic/parser/TimeParserUtilTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/StorageStatsManagerTest.java
  src/test/java/seedu/address/storage/appointment/JsonAppointmentBookStorageTest.java
  src/test/java/seedu/address/storage/archive/CsvAdaptedAppointmentTest.java
  src/test/java/seedu/address/storage/archive/CsvAdaptedPatientTest.java
  src/test/java/seedu/address/storage/patient/JsonPatientBookStorageTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
Labels: type.Testing :pencil2:

#188 Fix bug in schedule manager
  src/main/java/seedu/address/model/ScheduleManager.java
Labels: severity.High :skull:, type.Bug :bug:

#184 Dg update [done] [undo/redo]
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/DoneSequenceDiagram.puml
  docs/diagrams/UndoRedoState0.puml
  docs/diagrams/UndoRedoState1.puml
  docs/diagrams/UndoRedoState2.puml
  docs/diagrams/UndoRedoState3.puml
  docs/diagrams/UndoRedoState4.puml
  docs/diagrams/UndoRedoState5.puml
  docs/diagrams/UndoSequenceDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/DoneSequenceDiagram.png
  docs/images/UndoRedoState0.png
  docs/images/UndoRedoState1.png
  docs/images/UndoRedoState2.png
  docs/images/UndoRedoState3.png
  docs/images/UndoRedoState4.png
  docs/images/UndoRedoState5.png
  docs/images/UndoSequenceDiagram.png
Labels: type.Documentation :memo:

#185 Fix mock pe bugs
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/ChangeCommand.java
  src/main/java/seedu/address/logic/parser/ChangeCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/patient/Nric.java
  src/main/java/seedu/address/model/patient/Remark.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/patient/RemarkTest.java
Labels: type.Bug :bug:

#189 Add tests for ChangeCommand and Parser
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/commands/ChangeCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/ChangeCommandParserTest.java
Labels: type.Testing :pencil2:

#187 Update documentation
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchiveActivityDiagram.puml
  docs/images/ArchiveActivityDiagram.png
  docs/team/jinhao-l.md
  src/test/java/seedu/address/logic/parser/ChangeCommandParserTest.java
Labels: type.Documentation :memo:

#195 Update PPP, UserGuide and DeveloperGuide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AvailableCommandActivityDiagram.puml
  docs/diagrams/AvailableSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/AddCommand1.png
  docs/images/AddCommand2.png
  docs/images/AvailCommand1.png
  docs/images/AvailCommand2.png
  docs/images/AvailableCommandActivityDiagram.png
  docs/images/AvailableSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/team/xz0127.md
Labels: type.Documentation :memo:

#196 Update UG documentation
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/images/AppointmentCard.png
  docs/images/AppointmentOverview.png
  docs/images/CancelCommand.png
  docs/images/CancelCommand1.png
  docs/images/CancelCommand2.png
  docs/images/CancelCommand3.png
  docs/images/ClearCommand1.png
  docs/images/ClearCommand2.png
  docs/images/EditCommand.png
  docs/images/EditCommand1.png
  docs/images/EditCommand2.png
  docs/images/PatientCard.png
  docs/images/StatusDone.png
  docs/images/StatusExpired.png
  docs/images/StatusOngoing.png
  docs/images/StatusUpcoming.png
  docs/images/Ui.png
  docs/images/UiMarkup.png
  docs/images/helpMessage.png
Labels: type.Documentation :memo:

#200 Fix format
  docs/UserGuide.md
Labels: type.Documentation :memo:

#201 Fix find bug, Standardise message
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AvailableCommand.java
  src/main/java/seedu/address/logic/commands/ChangeCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/parser/AssignCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/appointment/Time.java
  src/test/java/seedu/address/logic/commands/ChangeCommandTest.java
  src/test/java/seedu/address/logic/commands/EditAppointmentDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindCommandParserTest.java
Labels: severity.High :skull:, type.Bug :bug:

#202 Adding line breaks
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/custom-styles.scss
  docs/diagrams/ModelClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/team/jinhao-l.md
  src/main/java/seedu/address/model/appointment/NaturalDay.java
  src/test/java/seedu/address/model/appointment/NaturalDayTest.java
Labels: type.Documentation :memo:

#204 Update User Guide
  docs/UserGuide.md
  docs/images/AddRemark2.png
  docs/images/ChangeCommand.png
  docs/images/ChangeCommandDate.png
  docs/images/ChangeCommandDate2.png
  docs/images/ChangeCommandTime.png
  docs/images/ChangeCommandTime2.png
  docs/images/CommandFormatAppt.png
  docs/images/CommandFormatDuration.png
  docs/images/CommandFormatPatient.png
  docs/images/DeleteCommand.png
  docs/images/DeleteCommand2.png
  docs/images/DeleteRemark.png
  docs/images/DeleteRemark2.png
  docs/images/ListCommand.png
  docs/images/ListCommand2.png
  docs/images/QuickStart.png
  docs/images/QuickStart2.png
  docs/images/QuickStart3.png
  docs/images/addRemark.png
  docs/images/nuudleLogo.png
  docs/team/avalionnet.md
Labels: type.Documentation :memo:
