Repository AY2021S1-CS2103T-T12-4/tp, pull requests merged in 2020-10, with the labels that each got.

#78 Add Appointment class
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/AppointmentComparator.java
  src/main/java/seedu/address/model/appointment/AppointmentId.java
  src/main/java/seedu/address/model/appointment/Date.java
  src/main/java/seedu/address/model/appointment/NaturalDay.java
  src/main/java/seedu/address/model/appointment/Time.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/test/java/seedu/address/model/appointment/AppointmentComparatorTest.java
  src/test/java/seedu/address/model/appointment/AppointmentIdTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/DateTest.java
  src/test/java/seedu/address/model/appointment/NaturalDayTest.java
  src/test/java/seedu/address/model/appointment/TimeTest.java
  src/test/java/seedu/address/testutil/AppointmentBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
Labels: priority.High

#80 Add Nric class
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Nric.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High

#96 Add RemarkCommand and RemarkCommand Parser
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/NuudleParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/patient/Nric.java
  src/main/java/seedu/address/model/patient/Patient.java
  src/main/java/seedu/address/model/patient/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPatient.java
  src/main/java/seedu/address/ui/PatientCard.java
  src/main/resources/view/PatientListCard.fxml
  src/test/data/JsonSerializablePatientBookTest/duplicatePatientPatientBook.json
  src/test/data/JsonSerializablePatientBookTest/typicalPatientsPatientBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.High, type.Story

#101 Update Version
  build.gradle
  src/main/java/seedu/address/MainApp.java
Labels: type.Task :construction:

#100 Upgrade constraints for Remark
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/index/Index.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/DateParserUtil.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/logic/parser/TimeParserUtil.java
  src/main/java/seedu/address/model/patient/Nric.java
  src/main/java/seedu/address/model/patient/Remark.java
  src/test/java/seedu/address/commons/core/index/IndexTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/patient/RemarkTest.java
  src/test/java/seedu/address/testutil/RemarkUtil.java
Labels: type.Enhancement :+1:

#109 Update Logic component in Developer's Guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/images/DeleteSequenceDiagram.png
  docs/images/LogicClassDiagram.png
Labels: type.Documentation :memo:

#110 Update Storage component in Developer's Guide
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: type.Documentation :memo:

#113 Update DG UI component and implementation of DoneCommand
  docs/DeveloperGuide.md
  docs/diagrams/DoneCommandActivityDiagram.puml
  docs/diagrams/DoneSequenceDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/DoneCommandActivityDiagram.png
  docs/images/DoneSequenceDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
Labels: type.Documentation :memo:

#103 Add a statistics box
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/AppointmentStatistics.java
  src/main/java/seedu/address/model/ReadOnlyAppointmentBook.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/model/appointment/Date.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/StatisticsDisplay.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticsDisplay.fxml
  src/test/java/seedu/address/model/AppointmentBookTest.java
  src/test/java/seedu/address/model/AppointmentStatisticsTest.java
  src/test/java/seedu/address/model/appointment/AppointmentTest.java
  src/test/java/seedu/address/model/appointment/DateTest.java
Labels: priority.Medium :2nd_place_medal:, type.Enhancement :+1:

#118 Dev Guide: add archive implementation
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchiveActivityDiagram.puml
  docs/diagrams/ArchiveSequenceDiagram.puml
  docs/diagrams/ArchiveStatusDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchiveActivityDiagram.png
  docs/images/ArchiveSequenceDiagram.png
  docs/images/ArchiveStatusDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/findAlexDavidResult.png
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/ui/PatientCard.java
Labels: type.Documentation :memo:

#121 UG: Add change command and update remarks
  docs/UserGuide.md
  docs/images/addRemark.jpg
  docs/images/deleteRemark.jpg
Labels: type.Documentation :memo:

#122 Update User Guide
  docs/UserGuide.md
  docs/images/ChangeCommand.png
  docs/images/ChangeCommand.png.kra
  docs/images/ChangeCommand.png~
  docs/images/addRemark.png
  docs/images/addRemark.png.kra
  docs/images/nullRemark.png
  docs/images/nullRemark.png.kra
Labels: type.Documentation :memo:

#106 Find available slots in a day
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/commons/util/TimeConversionUtil.java
  src/main/java/seedu/address/logic/commands/AvailableCommand.java
  src/main/java/seedu/address/logic/parser/AvailableCommandParser.java
  src/main/java/seedu/address/logic/parser/NuudleParser.java
  src/main/java/seedu/address/model/AppointmentBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ScheduleManager.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/model/interval/AnnotatedPointOfTime.java
  src/main/java/seedu/address/model/interval/PointOfTimeType.java
  src/main/java/seedu/address/model/interval/TimeInterval.java
  src/main/java/seedu/address/model/interval/TimeIntervalList.java
  src/test/java/seedu/address/commons/util/TimeConversionUtilTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AvailableCommandTest.java
  src/test/java/seedu/address/logic/parser/AvailableCommandParserTest.java
  src/test/java/seedu/address/model/ScheduleManagerTest.java
  src/test/java/seedu/address/model/interval/AnnotatedPointOfTimeTest.java
  src/test/java/seedu/address/model/interval/TimeIntervalListTest.java
  src/test/java/seedu/address/model/interval/TimeIntervalTest.java
  src/test/java/seedu/address/testutil/TimeIntervalListBuilder.java
  src/test/java/seedu/address/testutil/TypicalAppointments.java
  src/test/java/seedu/address/testutil/TypicalTimeIntervals.java
Labels: type.Enhancement :+1:

#123 Corrupted data handling
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/storage/AppointmentBookStorage.java
  src/main/java/seedu/address/storage/JsonAppointmentBookStorage.java
  src/main/java/seedu/address/storage/JsonPatientBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAppointmentBook.java
  src/main/java/seedu/address/storage/JsonSerializablePatientBook.java
  src/main/java/seedu/address/storage/PatientBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/UserPrefsStorage.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StatisticsDisplay.fxml
  src/test/data/JsonSerializablePatientBookTest/duplicatePatientBook.json
  src/test/java/seedu/address/model/AppointmentStatisticsTest.java
  src/test/java/seedu/address/storage/JsonAppointmentBookStorageTest.java
  src/test/java/seedu/address/storage/JsonPatientBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAppointmentBookTest.java
  src/test/java/seedu/address/storage/JsonSerializablePatientBookTest.java
Labels: type.Enhancement :+1:

#128 Command history
  docs/diagrams/LogicClassDiagram.puml
  docs/images/LogicClassDiagram.png
  src/main/java/seedu/address/logic/CommandHistory.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/CommandBox.fxml
  src/test/java/seedu/address/logic/CommandHistoryTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
Labels: type.Enhancement :+1:

#137 Fix json and tests inconsistency
  src/test/data/JsonAppointmentBookStorageTest/overlappingAppointmentBook.json
  src/test/data/JsonSerializableAppointmentBookTest/overlappingAppointmentBook.json
  src/test/data/JsonSerializableAppointmentBookTest/typicalAppointmentBook.json
  src/test/data/JsonSerializablePatientBookTest/typicalPatientBook.json
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/testutil/PatientBuilder.java
  src/test/java/seedu/address/testutil/TypicalPatients.java
Labels: priority.High :1st_place_medal:, type.Bug :bug:

#114 Add ChangeCommand and Parser
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/ChangeCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/ChangeCommandParser.java
  src/main/java/seedu/address/logic/parser/NuudleParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/appointment/UniqueAppointmentList.java
  src/main/java/seedu/address/ui/AppointmentCard.java
  src/main/java/seedu/address/ui/AppointmentListPanel.java
  src/main/resources/view/AppointmentListCard.fxml
Labels: priority.Medium :2nd_place_medal:, type.Enhancement :+1:

#125 Undo/Redo implementation
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/ChangeCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RedoCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/UndoCommand.java
  src/main/java/seedu/address/logic/parser/NuudleParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/VersionedAppointmentBook.java
  src/main/java/seedu/address/model/VersionedPatientBook.java
  src/main/java/seedu/address/model/exceptions/NoRedoableStateException.java
  src/main/java/seedu/address/model/exceptions/NoUndoableStateException.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/AssignCommandTest.java
  src/test/java/seedu/address/logic/commands/CancelCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/RedoCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/commands/UndoCommandTest.java
  src/test/java/seedu/address/model/VersionedAppointmentBookTest.java
  src/test/java/seedu/address/model/VersionedPatientBookTest.java
Labels: type.Enhancement :+1:

#133 Add implementation details for Remark in Dev Guide
  RemarkSequenceDiagram.png
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/RemarkClassDiagram.puml
  docs/diagrams/RemarkCommandActivityDiagram.puml
  docs/diagrams/RemarkLogicClassDiagram.drawio
  docs/diagrams/RemarkModelSequenceDiagram.puml
  docs/diagrams/RemarkParserRefSequenceDiagram.puml
  docs/diagrams/RemarkPathwaysActivityDiagram.puml
  docs/diagrams/RemarkSequenceDiagram.puml
  docs/images/RemarkClassDiagram.png
  docs/images/RemarkCommandActivityDiagram.png
  docs/images/RemarkLogicClassDiagram.png
  docs/images/RemarkLogicClassDiagram2.png
  docs/images/RemarkModelSequenceDiagram.png
  docs/images/RemarkParserRefSequenceDiagram.png
  docs/images/RemarkPathwaysActivityDiagram.png
  docs/images/RemarkSequenceDiagram.png
Labels: type.Documentation :memo:

#111 Archive past appointments to CSV
  build.gradle
  docs/UserGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/images/StorageClassDiagram.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/commons/util/CsvUtil.java
  src/main/java/seedu/address/commons/util/FileUtil.java
  src/main/java/seedu/address/commons/util/JsonUtil.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/appointment/Appointment.java
  src/main/java/seedu/address/storage/AppointmentArchive.java
  src/main/java/seedu/address/storage/AppointmentBookStorage.java
  src/main/java/seedu/address/storage/CsvAdaptedAppointment.java
  src/main/java/seedu/address/storage/CsvAdaptedPatient.java
  src/main/java/seedu/address/storage/CsvAppointmentArchive.java
  src/main/java/seedu/address/storage/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/JsonAppointmentBookStorage.java
  src/main/java/seedu/address/storage/JsonPatientBookStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAppointmentBook.java
  src/main/java/seedu/address/storage/JsonSerializablePatientBook.java
  src/main/java/seedu/address/storage/PatientBookStorage.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/StorageStatsManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/data/CsvAppointmentArchiveTest/notCsvFormat.csv
  src/test/data/CsvAppointmentArchiveTest/test.csv
  src/test/data/CsvAppointmentArchiveTest/validCsvArchive.csv
  src/test/java/seedu/address/commons/util/CsvUtilTest.java
  src/test/java/seedu/address/commons/util/JsonUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/storage/CsvAdaptedAppointmentTest.java
  src/test/java/seedu/address/storage/CsvAdaptedPatientTest.java
  src/test/java/seedu/address/storage/CsvAppointmentArchiveTest.java
  src/test/java/seedu/address/storage/JsonAppointmentBookStorageTest.java
  src/test/java/seedu/address/storage/JsonPatientBookStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableAppointmentBookTest.java
  src/test/java/seedu/address/storage/JsonSerializablePatientBookTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/StorageStatsManagerTest.java
  src/test/java/seedu/address/testutil/EditPatientDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PatientUtil.java
  src/test/java/seedu/address/testutil/SerializableCsvTestClass.java
  src/test/java/seedu/address/testutil/SerializableJsonTestClass.java
Labels: priority.High :1st_place_medal:, type.Enhancement :+1:

#135 Update edit feature implementation details in DG
  docs/DeveloperGuide.md
  docs/diagrams/EditActivityDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/images/EditActivityDiagram.png
  docs/images/EditCommandActivityDiagram.png
  docs/images/EditSequenceDiagram.png
Labels: type.Documentation :memo:

#138 Use index for cancel and done command
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/helpMessage.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/commands/AssignCommand.java
  src/main/java/seedu/address/logic/commands/CancelCommand.java
  src/main/java/seedu/address/logic/commands/ChangeCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/DoneCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/CancelCommandParser.java
  src/main/java/seedu/address/logic/parser/DoneCommandParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/resources/view/HelpWindow.fxml
  src/test/java/seedu/address/logic/commands/CancelCommandTest.java
  src/test/java/seedu/address/logic/commands/DoneCommandTest.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/CancelCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DoneCommandParserTest.java
  src/test/java/seedu/address/model/AppointmentBookTest.java
Labels: type.Documentation :memo:, type.Enhancement :+1:

#139 Update UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/ArchiveSequenceDiagram.puml
  docs/diagrams/ArchiveStatusDiagram.puml
  docs/diagrams/AssignModelClassDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/diagrams/DoneSequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/RemarkLogicClassDiagram.drawio
  docs/diagrams/RemarkLogicClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/ArchiveSequenceDiagram.png
  docs/images/ArchiveStatusDiagram.png
  docs/images/AssignModelClassDiagram.png
  docs/images/BetterModelClassDiagram.png
  docs/images/DeleteSequenceDiagram.png
  docs/images/DoneSequenceDiagram.png
  docs/images/EditSequenceDiagram.png
  docs/images/LogicClassDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/RemarkClassDiagram.png
  docs/images/RemarkLogicClassDiagram.png
  docs/images/RemarkLogicClassDiagram2.png
  docs/images/StorageClassDiagram.png
  docs/images/Ui.png
  docs/images/UiMarkup.png
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/storage/appointment/AppointmentBookStorage.java
  src/main/java/seedu/address/storage/appointment/JsonAdaptedAppointment.java
  src/main/java/seedu/address/storage/appointment/JsonAppointmentBookStorage.java
  src/main/java/seedu/address/storage/appointment/JsonSerializableAppointmentBook.java
  src/main/java/seedu/address/storage/archive/AppointmentArchive.java
  src/main/java/seedu/address/storage/archive/CsvAdaptedAppointment.java
  src/main/java/seedu/address/storage/archive/CsvAdaptedPatient.java
  src/main/java/seedu/address/storage/archive/CsvAppointmentArchive.java
  src/main/java/seedu/address/storage/patient/JsonAdaptedPatient.java
  src/main/java/seedu/address/storage/patient/JsonAdaptedTag.java
  src/main/java/seedu/address/storage/patient/JsonPatientBookStorage.java
  src/main/java/seedu/address/storage/patient/JsonSerializablePatientBook.java
  src/main/java/seedu/address/storage/patient/PatientBookStorage.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/storage/appointment/JsonAdaptedAppointmentTest.java
  src/test/java/seedu/address/storage/appointment/JsonAppointmentBookStorageTest.java
  src/test/java/seedu/address/storage/appointment/JsonSerializableAppointmentBookTest.java
  src/test/java/seedu/address/storage/archive/CsvAdaptedAppointmentTest.java
  src/test/java/seedu/address/storage/archive/CsvAdaptedPatientTest.java
  src/test/java/seedu/address/storage/archive/CsvAppointmentArchiveTest.java
  src/test/java/seedu/address/storage/patient/JsonAdaptedPatientTest.java
  src/test/java/seedu/address/storage/patient/JsonPatientBookStorageTest.java
  src/test/java/seedu/address/storage/patient/JsonSerializablePatientBookTest.java
Labels: type.Documentation :memo:

#142 Fix bug in available command
  src/main/java/seedu/address/model/ScheduleManager.java
Labels: severity.High :skull:, type.Bug :bug:
